#
#--Makefile to remake the executable and copy to this directory
#  Generated by ../phantom/scripts/writemake.sh: Sat May 16 13:56:16 AEST 2026
#
PHANTOMDIR=../phantom/
SPLASHDIR=/home/mboyle/splash
EDITOR=vi
ifndef SETUP
SETUP=solarsystem
endif

# MAXPTMASS must exceed the actual sink count produced by phantomsetup, not just np_apophis.
# The close-packed lattice overshoots the requested np_apophis by ~2-3% (e.g. 1000 -> 1012),
# so the default MAXPTMASS=1000 causes phantomsetup to abort with
# "ERROR: nptmass=1012 exceeds ptmass array dimensions of 1000".
ifndef MAXPTMASS
MAXPTMASS=2000
endif

again:
	set -e; cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} MAXPTMASS=${MAXPTMASS}; cd -; cp ${PHANTOMDIR}/bin/phantom .; cp ${PHANTOMDIR}/bin/phantom_version .

all: again setup infile

.PHONY: phantom phantomsetup phantom2power phantom2grid phantomanalysis phantomevcompare libphantom mflow
phantom         : again
phantomsetup    : setup
phantom2power   : power
phantom2grid    : grid
phantomanalysis : analysis
phantomevcompare: evcompare
phantomsinks    : sinks
libphantom      : phantomlib
mflow           : mflow

clean:
	cd ${PHANTOMDIR}; make clean
setup:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} MAXPTMASS=${MAXPTMASS} setup; cd -; cp ${PHANTOMDIR}/bin/phantomsetup .
moddump:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} moddump; cd -; cp ${PHANTOMDIR}/bin/phantommoddump .
analysis:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} analysis; cd -; cp ${PHANTOMDIR}/bin/phantomanalysis .
phantomlib:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} libphantom; cd -; cp ${PHANTOMDIR}/bin/libphantom.so .
pyanalysis:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} pyanalysis; cd -; cp ${PHANTOMDIR}/bin/libphantom.so .; ${PHANTOMDIR}/scripts/pyphantom/writepyanalysis.sh 
power:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} phantom2power; cd -; cp ${PHANTOMDIR}/bin/phantom2power .
grid:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} phantom2grid; cd -; cp ${PHANTOMDIR}/bin/phantom2grid .
evcompare:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} phantomevcompare; cd -; cp ${PHANTOMDIR}/bin/phantomevcompare .
sinks:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} phantomsinks; cd -; cp ${PHANTOMDIR}/bin/phantomsinks .
mflow:
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} mflow; cd -; cp ${PHANTOMDIR}/bin/mflow .; cp ${PHANTOMDIR}/bin/ev2mdot .; cp ${PHANTOMDIR}/bin/lombperiod .
make:
	cd ${PHANTOMDIR}; ${EDITOR} build/Makefile &
qscript:
	@cd ${PHANTOMDIR}; make --quiet RUNDIR="${PWD}" SETUP=${SETUP} qscript
%::
	cd ${PHANTOMDIR}; make RUNDIR="${PWD}" SETUP=${SETUP} ${MAKECMDGOALS}; if [ -e ${PHANTOMDIR}/bin/$@ ]; then cd -; cp ${PHANTOMDIR}/bin/$@ .; fi
#
# the following are for rebuilding splash
#
plot:
	cd ${SPLASH_DIR}; make sphNG
plotc:
	cd ${SPLASH_DIR}; make clean
